---
on:
  push:
    branches:
      - 'master'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run wp
      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
