---
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run wp
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download build result
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: bundle result
        run: tar czf fabric.tar.gz ux.js main.js index.html styles.css
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "fabric.tar.gz,main.js,ux.js,index.html,styles.css"
